const ACTIONS = {
  IS_LOGGED: "IS_LOGGED",
  IS_ADMIN: "IS_ADMIN",
  ERROR: "ERROR",
  SUCCESS: "SUCCESS",
  TRANSITION: "TRANSITION",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
};

export default ACTIONS;
